version: '3'

services:
  agile-lora:
    container_name: cayenne-adapter
    image: vicinity/cayenne-adapter
    build: ./
    # volumes:      
      # - ../protocol:/usr/src/app
    environment:
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/usr/src/app/.agile_bus/agile_bus_socket  
      - LORAWAN_APP_SERVER=TTN
      - LORAWAN_APPID=ari_ioe_app_demo1
      - LORAWAN_PSW=ttn-account-v2.UitfM5cPazqW52_zbtgUS6wM5vp1MeLC9Yu-Cozjfp0
      - LORAWAN_MQTT_URL=eu.thethings.network   
      - LORAWAN_MQTT_PORT=1883      
    ports:
      - 9995:9995/tcp
    restart: always    
    network_mode: "host"